# keywords that should not have start_keyword logs
start_keyword_skip_list = [
    # BuiltIn
    "Comment",
    "Convert To Binary",
    "Convert To Boolean",
    "Convert To Bytes",
    "Convert To Hex",
    "Convert To Integer",
    "Convert To Number",
    "Convert To Octal",
    "Convert To String",
    "Create Dictionary",
    "Create List",
    "Exit For Loop If",
    "Get Count",
    "Get Length",
    "Get Library Instance",
    "Get Time",
    "Get Variable Value",
    "Get Variables",
    "Import Library",
    "Import Resource",
    "Import Variables",
    "Keyword Should Exist",
    "Length Should Be",
    "No Operation",
    "Pass Execution",
    "Pass Execution If",
    "Regexp Escape",
    "Reload Library",
    "Remove Tags",
    "Repeat Keyword",
    "Replace Variables",
    "Reset Log Level",
    "Set Global Variable",
    "Set Log Level",
    "Set Suite Documentation",
    "Set Suite Metadata",
    "Set Suite Variable",
    "Set Tags",
    "Set Test Documentation",
    "Set Test Message",
    "Set Test Variable",
    "Set Variable",
    "Should Be Empty",
    "Should Be Equal",
    "Should Be Equal As Numbers",
    "Should Be Equal As Strings",
    "Should Be True",
    "Should Contain",
    "Should Contain X Times",
    "Should End With",
    "Should Match",
    "Should Match Regexp",
    "Should Not Be Empty",
    "Should Not Be Equal",
    "Should Not Be Equal As Integers",
    "Should Not Be Equal As Numbers",
    "Should Not Be Equal As Strings",
    "Should Not Be True",
    "Should Not Contain",
    "Should Not End With",
    "Should Not Match",
    "Should Not Match Regexp",
    "Should Not Start With",
    "Should Start With",
    "Skip",
    "Skip If",
    "Sleep",
    "Variable Should Exist",
    "Variable Should Not Exist",
    # Collections
    "Append To List",
    "Combine Lists",
    "Copy List",
    "Count List Items",
    "Get From Dictionary",
    "Get From List",
    "Get List Items",
    "Get Dictionary Keys",
    "Get Dictionary Values",
    "Insert Into List",
    "List Should Contain Value",
    "List Should Not Contain Value",
    "Log List",
    "Remove From Dictionary",
    "Remove From List",
    "Remove Values From List",
    "Set List Value",
    "Sort List",
    "Dictionary Should Contain Key",
    "Dictionary Should Not Contain Key",
    "Dictionary Should Contain Value",
    "Dictionary Should Not Contain Value",
    "Get Dictionary Items",
    "Get Dictionary Keys",
    "Get Dictionary Values",
    "Get List Items",
    "Get From Dictionary",
    "Get From List",
    "List Should Contain Value",
    "List Should Not Contain Value",
    "Remove From Dictionary",
    "Remove From List",
    "Remove Values From List",
    "Set List Value",
    "Sort List"
    # DateTime
    "Add Time To Date",
    "Add Time To Time",
    "Convert Date",
    "Convert Time",
    "Get Current Date",
    "Subtract Date From Date",
    "Subtract Time From Date",
    "Subtract Time From Time",
    # Dialogs
    "Execute Manual Step",
    "Get Selection From User",
    "Get Selections From User",
    "Get Value From User",
    "Pause Execution",
    # OperatingSystem
    "Append To Environment Variable",
    "Append To File",
    "Copy Directory",
    "Copy File",
    "Copy Files",
    "Copy Directory",
    "Copy File",
    "Copy Files",
    "Count Directories In Directory",
    "Count Files In Directory",
    "Count Items In Directory",
    "Create Binary File",
    "Create Directory",
    "Create File",
    "Directory Should Be Empty",
    "Directory Should Exist",
    "Directory Should Not Be Empty",
    "Directory Should Not Exist",
    "Empty Directory",
    "Environment Variable Should Be Set",
    "Environment Variable Should Not Be Set",
    "File Should Be Empty",
    "File Should Exist",
    "File Should Not Be Empty",
    "File Should Not Exist",
    "Get Binary File",
    "Get Environment Variable",
    "Get Environment Variables",
    "Get File",
    "Get File Size",
    "Get Modified Time",
    "Grep File",
    "Join Path",
    "Join Paths",
    "List Directories In Directory",
    "List Directory",
    "List Files In Directory",
    "Log Files In Directory",
    "Log Environment Variables",
    "Log File",
    "Move Directory",
    "Move File",
    "Move Files",
    "Normalize Path",
    "Remove Directory",
    "Remove Environment Variable",
    "Remove File",
    "Remove Files",
    "Run",
    "Run And Return Rc",
    "Run and Return Rc And Output",
    "Set Environment Variable",
    "Set Modified Time",
    "Should Exist",
    "Should Not Exist",
    "Split Extension",
    "Split Path",
    "Touch",
    "Wait Until Created",
    "Wait Until Removed"
]

# keywords that should not have end_keyword traces
end_keyword_skip_list = [
    "Comment",
    "Log To Console",
    "Log",
    "Log Many"
]

# keywords whose logs shouuld not add a new line
newline_skip_list = [
    "Log To Console"
]

# path to out folder
PATH_TO_OUTPUT = "../out/"